<?php

function vzbv_scm_feeds_cmis_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
	$field_types = array();

	$field_types[] = 'cmis_field_path';

	foreach (field_info_instances($entity_type, $bundle_name) as $name => $instance) {
		$info = field_info_field($name);

		if (in_array($info['type'], $field_types)) {
			$targets[$name] = array(
				'name' => t('@label (cmis_field)', array('@label' => $instance['label'])),
				'callback' => 'vzbv_scm_feeds_cmis_set_target',
				'description' => t('The @label field of the node. Consuming file paths and uploading into CMIS-Endpoint')
			);
		}
	}

}

function vzbv_scm_feeds_cmis_set_target($source, $entity, $target, $values, $config = array()) {
  if (empty($values)) {
    return;
  }

  if (!is_array($values)) {
    $values = array($values);
  }

  $field_info = field_info_field($target);
  $field = array(LANGUAGE_NONE => array());

  module_load_include('api.inc', 'cmis');

  $instance = field_info_instance($entity->feeds_item->entity_type, $target, $entity->type);

  dpm($instance, 'Field Instance');
  if (isset($instance['settings']['cmis_field_rootFolderPath'])) {
    $folder_path = $instance['settings']['cmis_field_rootFolderPath'];
  }
  else {
    drupal_set_message('CMIS Field has no configured Root Folder Path, please set one and retry', 'error');
    return FALSE;
  }

  dpm($folder_path, 'Import Root Folder');


  foreach ($values as $value) {
    $document_name = basename($value);
    $document_public_url = file_create_url($value);
    $document_content = file_get_contents($document_public_url);
    $document_mimetype = file_get_mimetype($value);


    dpm($document_name, "Document File Name");

    try {
      $repository = cmis_get_repository();
      $folder = cmisapi_getObjectByPath($repository->repositoryId, $folder_path);
    }
    catch (CMISException $e) {
      drupal_set_message(
        t('Failed to read from CMIS Repository, check your connection: %value',
        array('%value' => (string) $e)), 'error');
      return FALSE;
    }

    if ($folder->properties['cmis:baseTypeId'] == 'cmis:folder') {
      try {
        $document = cmisapi_getObjectByPath($repository->repositoryId, implode("/", array($folder_path, $document_name)));
      }
      catch (CMISException $e) {
        dpm($e, 'Get Document Error');

        try {
          $document = cmisapi_createDocument($repository->repositoryId, $folder->id, $document_name, array(), $document_content, $document_mimetype, array('title' => $document_name));
          drupal_set_message(t('CMIS object @object_name has been created.', array('@object_name' => $document_name)));

          $result = array(
            'path' => $document->id,
            'title' => $document_name,
          );

          dpm($result);

          $field[LANGUAGE_NONE][] = $result;

          $entity->{$target} = $field;
        }
        catch (CMISException $e) {
          drupal_set_message(t('Unable to create @object_name object. @error', array('@object_name' => $document_name, '@error' => $e)), 'error');
          return '';
        }
      }
    }
    else {
      drupal_set_message(t('Error while locating the target space @object_id', array('@object_id' => $folder_path)), 'error');
    }
  }

}